interpolation:
    method: 'cubic'
    Dust:
        beta: 
            low: -3.5
            high: 6.5
            N: 1_000

        T:
            low: 5
            high: 45
            N: 1_000
    Synch:
        beta:
            low: -8
            high: 2
            N: 10_000