interpolation:
    method: 'cubic'
    Dust:
        beta: 
            low: -0.5
            high: 3.5
            N: 1_001

        T:
            low: 5
            high: 45
            N: 1_001
    Synch:
        beta:
            low: -6.0
            high: 0.0
            N: 1_001